---
# file roles/java/tasks/main.yml 

- debug:
    msg: "java role started..."

# -----------------------------------------------------------
# NOTE: if these packages are not installed, headless systems
#       will report problems with java.awt.headless like this
#       "awt is not properly configured on this server"

      ## - name: Install required packages 
      ##   package:
      ##     name: "{{ item }}"
      ##     state: present
      ##   with_items:
      ##     - fonts-dejavu-core
      ##     - xvfb
      ##     - libfonts-java
      ##     - libfontconfig1

# -----------------------------------------------------------

- name: install java V {{ java_version }} using {{ debian_java_package }}
  package:
    name: "{{ debian_java_package }}"
    state: present

# -----------------------------------------------------------

- debug:
    msg: "Setting JAVA_HOME"

- name: find java binary 
  command: update-alternatives --list java
  register: java_binary

- debug:
    var: java_binary.stdout

- name: find java home
  shell: "java -XshowSettings:properties -version 2>&1 | grep java.home | sed 's/ //g' | cut -d '=' -f2"
  register: java_home_dir 

- debug:
    var: java_home_dir.stdout

- name: remove any previous java home definitions
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME'
    state: absent

- name: set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    line: JAVA_HOME={{ java_home_dir.stdout }}

- debug:
    msg: "java role finished..."

##

