---
# roles/kafka_kraft/defaults/main.yml
#
# kafka_version: 3.9.0
kafka_version: '4.0.0'
##
scala_version: '2.13'
#
kafka_url: https://archive.apache.org/dist/kafka/{{ kafka_version }}
kafka_package: kafka_{{ scala_version }}-{{ kafka_version }}
#
kafka_suffix: ".tgz"
kafka_temp_dir: /tmp
kafka_home: /var/lib/kafka
kafka_user: kafka
kafka_group: kafka
#
# NOTE: default for this is /tmp, bad as /tmp is cleaned periodically
#       /var/log is also not good idea, since log_rotate is run on it
#       Thus, is defined assuming will be mapped by symlink to target
kafka_broker_logs: /kafka_broker_logs
#
kafka_test: true
###  
##


