---
# tokengine/infra/ansible/site.yml
#
# NOTE: this should exist in your ansible.cfg file:
# [privilege_escalation]
# become=True

- hosts: tokengine
  roles:
    - { role: hostname, tags: ["hostname"] }
    - { role: docker_install, tags: ["docker"] }
    - { role: caddy, tags: ["caddy"] }

##

