---
# tokengine/infra/ansible/site.yml
#
# NOTE: this should exist in your ansible.cfg file:
# [privilege_escalation]
# become=True

- hosts: tok1
  roles:
    - { role: hostname, tags: ["hostname"] }
    - { role: set_uuid, tags: [ "uuid"] }
    - { role: java, tags: ["java"] }
    - { role: tokengine, tags: ["tokengine"] }
    - { role: caddy, tags: ["caddy"] }

- hosts: tke-1
  roles:
    - { role: hostname, tags: ["hostname"] }
    - { role: set_uuid, tags: [ "uuid"] }
    - { role: java, tags: ["java"] }
    - { role: tokengine, tags: ["tokengine"] }
    - { role: caddy, tags: ["caddy"] }

- hosts: tke-2
  roles:
    - { role: hostname, tags: ["hostname"] }
    - { role: set_uuid, tags: [ "uuid"] }
    - { role: java, tags: ["java"] }
    - { role: tokengine, tags: ["tokengine"] }
    - { role: caddy, tags: ["caddy"] }

##

