---
# tokengine/infra/roles/caddy/tasks/main.yml
#
# NOTE: will install caddy only if not aldready installed.
#       To upgrade to a later version of caddy, delete the
#       Caddyfile & re-run the Ansible playbook, defining
#       the caddy tag with --tags caddy on the command line
#       This play can be run any number of times against 
#       an installed version of Caddy, e.g. to update the
#       Caddyfile from definitions in host_vars/caddy.yml

- name: check if caddy installed
  ansible.builtin.stat:
    path: "{{ caddy_file }}"
  register: stat_result

- name: run caddy_install tasks
  # NOTE: does not generate Caddyfile
  ansible.builtin.include_tasks: caddy_install.yml
  when: "stat_result.stat.exists == False"

# --------------------------------------------------------

- name: run caddy_config tasks
  # this generates Caddyfile and Caddydoc.txt
  ansible.builtin.include_tasks: caddy_config.yml
  tags: caddy_config

# --------------------------------------------------------

- name: add caddy to /etc/logrotate.d
  ansible.builtin.template:
    src: caddy_logrotate.j2
    dest: /etc/logrotate.d/caddy
    owner: root
    group: root
    mode: 0644


##

