---
# roles/tokengine/tasks/main.yml
#
- name: create tokengine group
  ansible.builtin.group:
    name: "{{ tokengine_group }}"
    state: present

- name: create tokengine user
  ansible.builtin.user:
    name: "{{ tokengine_user }}"
    group: "{{ tokengine_group }}"
    shell: "/bin/bash"

      # - name: ensure download directory exists
      #   ansible.builtin.file:
      #     path: Downloads
      #     state: directory

- name: ensure tokengine homedir {{ tokengine_homedir }} exists
  ansible.builtin.file:
    path: "{{ tokengine_homedir }}"
    state: directory
    owner: root
    group: root

- name: remove any previous {{ tokengine_package }} file from {{ tokengine_homedir }}
  ansible.builtin.file:
    path: "{{ tokengine_homedir }}/{{ tokengine_package }}"
    state: absent

- name: upload files/{{ tokengine_package }} to {{ tokengine_homedir }}
  ansible.builtin.copy:
    src: files/{{ tokengine_package }}
    dest: "{{ tokengine_homedir }}"
      # owner: "{{ tokengine_user }}"
      # group: "{{ tokengine_group }}"
    owner: root
    group: root

- name: ensure directory /home/{{ tokengine_user }}/.tokengine exists
  ansible.builtin.file:
    path: "/home/{{ tokengine_user }}/.tokengine"
    state: directory
    owner: "{{ tokengine_user }}"
    group: "{{ tokengine_group }}"

- name: upload files/config.json to /home/{{ tokengine_user }}/.tokengine
  ansible.builtin.copy:
    src: files/config.json
    dest: "/home/{{ tokengine_user }}/.tokengine/config.json"
    owner: root
    group: root

- name: fix owner/group on {{ tokengine_homedir }}/{{ tokengine_path }}/ dir
  ansible.builtin.command: "chown -R {{ tokengine_user }}:{{ tokengine_group }} {{ tokengine_homedir }}"
  
    # - name: symlink {{ tokengine_homedir }}/{{ tokengine_path }} to tokengine
    #   file:
    #     src: "{{ tokengine_homedir }}/{{ tokengine_path }}"
    #     dest: "{{ tokengine_homedir }}/tokengine"
    #     state: link
    
- name: create tokengine systemd script
  template:
    src: tokengine.service.j2
    dest: /etc/systemd/system/tokengine.service
    owner: root
    group: root
    mode: 0644

- name: run systemctl daemon-reload
  shell: systemctl daemon-reload

- name: ensure tokengine service started on boot and enabled
  service:
    name: tokengine
    state: started
    enabled: yes

##



